// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChartConfigModal: typeof import('../components/ChartConfigModal.vue')['default'];
    ChartWidget: typeof import('../components/ChartWidget.vue')['default'];
  }
}

export {};
